name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - 'slack-integration/*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Notification
      uses: SandeepKumarYaramchitti/UniNotify@v1
      with:
        messageType: 'slack' # Or 'teams' or 'chime'
        message: 'A new release has been published!'
        slackToken: ${{ secrets.SLACK_API_TOKEN }} # For Slack, you would use a Slack API token
